apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-notify-config
  labels:
    app: flask-notify
data:
  POSTGRES_DB: appdb
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: pass123
  REDIS_SERVER: redis-server
  REDIS_PASS: pass123
  DB_HOST: psql-db
  DB_PORT: "5432"
  DB_USER: appuser
  DB_PASSWORD: pass123
  DB_NAME: appdb


