apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-notify-config
  labels:
    app: flask-notify
data:
  MAIL_SERVER: "linux110.papaki.gr"
  MAIL_PORT: "465"
  MAIL_USERNAME: "info@public-services.site"
  MAIL_PASSWORD: "pas!!123"
  MAIL_USE_TLS: "False"
  MAIL_USE_SSL: "True"


